const fs = require('fs');
const path = require('path');

const buildDir = path.join(__dirname, '..', 'build');
const iconSource = path.join(__dirname, '..', 'public', 'app-iconpng.png');
const iconDestPng = path.join(buildDir, 'icon.png');
const iconDestIcns = path.join(buildDir, 'icon.icns');
const iconDestIco = path.join(buildDir, 'icon.ico');

if (!fs.existsSync(buildDir)) {
  fs.mkdirSync(buildDir, { recursive: true });
}

if (fs.existsSync(iconSource)) {
  fs.copyFileSync(iconSource, iconDestPng);
  console.log('Icon copied to build directory as icon.png');
  
  if (!fs.existsSync(iconDestIcns)) {
    fs.copyFileSync(iconSource, iconDestIcns);
    console.log('Created placeholder icon.icns (will be properly generated by electron-builder)');
  }
  
  if (!fs.existsSync(iconDestIco)) {
    fs.copyFileSync(iconSource, iconDestIco);
    console.log('Created placeholder icon.ico (will be properly generated by electron-builder)');
  }
} else {
  console.error('Source icon not found:', iconSource);
  process.exit(1);
}